name: 'Create new release'

on:
  push:
    branches:
      - main
    
jobs: 
  create_apk:
    name: Create apk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cinescope
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter: cinescope/pubspec.yaml
          flutter-version: 3.13.7
          cache: true
      - run: flutter build apk
      - name: Upload final apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: cinescope/build/app/outputs/apk/release

  deploy_release:
    name: Deploy Release
    runs-on: ubuntu-latest
    needs: create_apk
    defaults:
      run:
        working-directory: ./cinescope
    steps:
      - name: Download the .apk
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: app-release.apk


      
