name: 'Check for static errors'

on:
  push:
    branches:
      - main

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter: cinescope/pubspec.yaml
          flutter-version: 3.13.7
          cache: true
      - run: dart format . --set-exit-if-changed

  format:
    name: Formatter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cinescope
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.7
          cache: true
      - run: flutter analyze
  
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cinescope
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.7
          cache: true
      - run: flutter test